#!/usr/bin/env bash
set -e

# don't change these 4 lines
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TRAINING=$1;
INPUT=$2;
OUTPUT=$3;

# you should change the lines below

# prepare the training data
python $SCRIPTDIR/preprocess.py < $TRAINING | $SCRIPTDIR/unknown.py > $SCRIPTDIR/tmpfile
# you should probably do something with the file you just wrote
# (and you may not want to call it tmpfile). But in this stub code I'm just going
# to create a grammar without paying attention to the input
python $SCRIPTDIR/q1.py tmpfile > mygrammar
python $SCRIPTDIR/parser3.py -i $INPUT -r mygrammar -o tmpfile2
python $SCRIPTDIR/postprocess.py tmpfile2 > $OUTPUT

# run your parser on your input and save to your output. The provided parser is
# strictly right branching (cf. slides) and gets 12.4 f on dev. It ignores the grammar

# $SCRIPTDIR/rbranch.py -i $INPUT -o $OUTPUT

